Updated to install the latest version of tomcat

diff --git a/install_kuali_coeus b/install_kuali_coeus
--- a/install_kuali_coeus
+++ b/install_kuali_coeus
@@ -1,13 +1,31 @@
 #!/bin/bash
 
+function install_this_package () {
+	if [ -f /etc/debian_version ]; then
+		apt-get update
+		apt-get install -y $1
+	elif [ -f /etc/redhat-release ]; then
+		yum install -y $1
+	fi
+}
+
+function check_if_package_is_installed () {
+	command -v $1 >/dev/null 2>&1 || { echo >&2 "Couldn't find $1 on your system. Installing it: "; install_this_package $1; }
+}
+
 #DEFINE
 LINUX_DISTRIBUTATION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS)" /etc/issue)
 DISTRIBUTATION_VERSION=$(cat /etc/*release | grep VERSION_ID | cut -c 13)
 
 # TOMCAT RELATED
-TOMCAT_LINK="http://apache.mirrors.lucidnetworks.net/tomcat/tomcat-8/v8.0.21/bin/apache-tomcat-8.0.21.tar.gz"
-TOMCAT_FILE="apache-tomcat-8.0.21.tar.gz"
-TOMCAT_LOCATION="/opt/apache-tomcat/tomcat8"
+check_if_package_is_installed wget
+TOMCAT_MAJOR="8"
+wget --no-check-certificate https://tomcat.apache.org/download-${TOMCAT_MAJOR}0.cgi -O /tmp/get_version
+TOMCAT_VERSION=$(grep -A 7 '</select><input type="submit" value="Change">' /tmp/get_version | grep '<h3 id="' | sed 's/<h3 id="//' | sed 's/">.*//')
+TOMCAT_LINK="https://www.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
+TOMCAT_FILE="apache-tomcat-${TOMCAT_VERSION}.tar.gz"
+TOMCAT_LOCATION="/opt/apache-tomcat/tomcat${TOMCAT_MAJOR}"
+rm -f /tmp/get_version
 
 # MySQL Connector Java
 MYSQL_CONNECTOR_LINK="http://mirror.cogentco.com/pub/mysql/Connector-J/mysql-connector-java-5.1.34.zip"
